import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const avenir = localFont({
  src: [
    {
      path: "./fonts/Avenir/AvenirLTStd-Light.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Book.otf",
      weight: "400",
      style: "book",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Roman.otf",
      weight: "500",
      style: "roman",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Medium.otf",
      weight: "600",
      style: "medium",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Heavy.otf",
      weight: "800",
      style: "heavy",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Black.otf",
      weight: "900",
      style: "black",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-LightOblique.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-BookOblique.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-Oblique.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-MediumOblique.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-HeavyOblique.otf",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/Avenir/AvenirLTStd-BlackOblique.otf",
      weight: "900",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${avenir.className} mx-auto w-11/12 pt-8 antialiased lg:w-4/6`}
      >
        {children}
      </body>
    </html>
  );
}
